version: "2"
services:

  influxdb:
    build: ./influxdb
    env_file: ./.env
    ports:
      - "${INFLUXDB_HOST_PORT}:8086"
      - "${IMEX_PORT}:22"
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb:/var/lib/influxdb
    restart: always
    secrets:
      - ssh_login

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
      HOST_MOUNT_PREFIX: /host
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_HOST_PORT}:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - influxdb

  ruuvitag_app:
    build: ./ruuvitag_app
    env_file: ./.env
    privileged: true
    network_mode: "host"
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb:
  grafana-storage:

secrets:
  ssh_login:
    file: "${IMEX_PW_FILE}"
