# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: ruuvitag
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: ruuvitag
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://influxdb:8086
    # <string> database password, if used
    password:
    # <string> database user, if used
    user:
    # <string> database name, if used
    database: tag_data
    # <bool> enable/disable basic auth
    basicAuth: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    # <bool> allow users to edit datasources from the UI.
    editable: true
